### ISSUE TITLE
ENH: Support of language map

### ISSUE THREAD

**Issue by vcuende** [morph-kgc/morph-kgc#101]
I was working in a mapping of a dataset which contains 3 languages (English, German and Swedish) and I tried to differentiate an attribute (title of a job) by their language tag. However, after I used morph-kgc to generate the ntriples file, in the file itself the language tags that should have come for the attribute "title of a job" did not appear. It is not a severe problem, as all information was well generated, but I really missed the @en/@sv/@de language tags.

**Comment by ArenasGuerreroJulian** [comment]
Hi @vcuende ,

Morph-KGC supports [`rr:language`](https://www.w3.org/TR/r2rml/#language-tags) but no [`rml:languageMap`](https://rml.io/specs/rml/#language-tag) yet.

We will try to implement it in coming releases.
