### ISSUE TITLE
ENH: In-memory dictionary transformation

### ISSUE THREAD

**Issue by dgarijo** [morph-kgc/morph-kgc#131]
#### Is your Feature Request Related to a Problem?
I would like to pass an in-memory JSON dictionary for my conversion, instead of reading it from a source file. At the moment I have to save intermediate JSON results just for morph-kgc to re-read them again.

#### Describe the Solution you'd Like
A way to pass in a source which is in-memory, instead of written in a file

#### Describe Alternatives you've Considered
At the moment I have to do some processing, save an intermediate JSON file and update the paths in the config file so morph-kgc reads it

**Comment by TheRazorace** [comment]
This issue can be closed now, with the in-memory extension being added (see Examples -> dict)

**Comment by arenas-guerrero-julian** [comment]
Thanks @TheRazorace
