### ISSUE TITLE
BUG: Error in test fno RMLFNOTC0006-CSV

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#140]
####  What Happens?
The output of this test is not correct because this is not a triple: 
`<http://example.com/Venus> <http://xmlns.com/foaf/0.1/name> "Venus" <http://VENUS> .`

It seems that the correct output should be: 
`<http://example.com/Venus> <http://xmlns.com/foaf/0.1/name> <http://VENUS> .`

If so, this part of the mapping is  not correct: 
````
rr:predicateObjectMap [
        rr:predicate foaf:name;
        rr:objectMap [ rml:reference "Name"] ;
        rr:graphMap [
            fnml:execution <#Execution> ;
            rr:termType rr:IRI
        ];
    ] .
````
It should be:
````
rr:predicateObjectMap [
        rr:predicate foaf:name;
        rr:objectMap [ 
            fnml:execution <#Execution> ;
            rr:termType rr:IRI
        ];
    ] .
````
Is it right?

#### To Reproduce
See above

#### Environment
I'm testing the latest version of morph-kgc installed from the GitHub repository.

**Comment by arenas-guerrero-julian** [comment]
Hi @paoespinozarias 

Thanks for reporting this :) , you are right, I just fixed the test case.
