### ISSUE TITLE
BUG: controls_if function does not work with string values 

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#141]
####  What Happens?
I tested this function using a string value in the `rr:template` parameter but it trhows the following exception:
![image](https://user-images.githubusercontent.com/16767406/212884349-867edb17-e98f-4e76-b2a0-335079d18d5f.png)

The output should be the same than the one obtained when running the test as it is currently configured.

#### To Reproduce
I reused the same [calendar.csv](https://github.com/morph-kgc/morph-kgc/blob/main/test/fno/controls_if/calendar.csv) file from the test but I replaced 1 by X:

```
service_id | monday | tuesday | wednesday | thursday | friday | saturday | sunday | start_date | end_date
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 6/30/2017 | 6/30/2018
5 | X | X | X | X | X | X | X | 6/30/2017 | 6/30/2018
```

I reused the same [mapping.ttl](https://github.com/morph-kgc/morph-kgc/blob/main/test/fno/controls_if/mapping.ttl) file from the test but I changed a bit the Execution statements:

```
<#Execution1>
    fnml:function grel:controls_if ;
    fnml:input
        [
            fnml:parameter grel:bool_b ;
            fnml:valueMap [
                rr:template "X == {monday}"
            ]
        ] ,
        [
            fnml:parameter grel:any_true ;
            fnml:value "true"
        ] ,
        [
            fnml:parameter grel:any_false ;
            fnml:value "false"
        ] .

<#Execution2>
    fnml:function grel:controls_if ;
    fnml:input
        [
            fnml:parameter grel:bool_b ;
            fnml:valueMap [
                rr:template "X == {tuesday}"
            ]
        ] ,
        [
            fnml:parameter grel:any_true ;
            fnml:value "true"
        ] .
```

#### Environment (please complete the following information):
I'm testing the latest version of morph-kgc installed from the GitHub repository.

**Comment by arenas-guerrero-julian** [comment]
Hi @paoespinozarias ,

Could you please try with `rr:template "'X' == {monday}"`? Note the quotes around `X`.

**Comment by paoespinozarias** [comment]
Hi @arenas-guerrero-julian ,

Thank you for the support, this configuration works!

**Comment by arenas-guerrero-julian** [comment]
Thanks :)

This is because the expression evaluates to a Python expression. If no quotes are used, a variable (that does not exist) is assumed; using quotes it evaluates to a string.
