### ISSUE TITLE
BUG: udf test does not work

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#146]
####  What Happens?
I'm reproducing the same configuration you defined in the [udf test case](https://github.com/morph-kgc/morph-kgc/tree/main/test/fno/udf). However, when I execute the test I got the following exception: 

![image](https://user-images.githubusercontent.com/16767406/216661904-db80f8df-e0fa-4ed7-be15-9b8552d072be.png)

Should I define the `@udf` decorator somehow?

#### To Reproduce
See above

#### Environment (please complete the following information):
- OS: Windows 10
- Python version: 3.9.6
- Morph-KGC version: Latest version installed from the GitHub repository.

**Comment by arenas-guerrero-julian** [comment]
Hi @paoespinozarias ,

This is working for me. Is your script with udfs similar to [this](https://github.com/morph-kgc/morph-kgc/blob/main/test/fno/udf/udf.py)?

**Comment by paoespinozarias** [comment]
Hi @arenas-guerrero-julian ,

My error was not getting the latest version of the repository because you changed it to avoid using additional syntax in the udf configuration. So now the test is working :-)

Thanks for your help!
