### ISSUE TITLE
ENH: get output values of a function annoted in custom data types

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#148]
#### Is your Feature Request Related to a Problem?
I'm using custom data types to annotate values as, for example, units of measurement. Therefore, I need to be able to annotate the output value of a function as a custom data type.

#### Describe the Solution you'd Like
To illustrate this request I will use the configuration files of the [math_round](https://github.com/morph-kgc/morph-kgc/tree/main/test/fno/math_round)  function test.  The mapping I would like to configure looks as follows:

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .
@prefix fno: <https://w3id.org/function/ontology#> .
@prefix morph-kgc: <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix idlab-fn: <http://example.com/idlab/function/> .
@prefix unit: <http://example.com/unit/> .

@base <http://example.com/base/> .

<#Person_Mapping>
    rml:logicalSource [
        rml:source "distances.tsv";
        rml:referenceFormulation ql:CSV
    ];
    rr:subjectMap [
        rr:template "http://example.com/distance/{id}"
    ];
    rr:predicateObjectMap [
        rr:predicate ex:distance;
        rr:objectMap [
            fnml:execution <#Execution> ;
            rr:datatype unit:km
        ]
    ].

<#Execution>
    fnml:function grel:math_round ;
    fnml:input
        [
            fnml:parameter grel:param_dec_n ;
            fnml:valueMap [
                rml:reference "distance_km"
            ]
        ] .
```
Note that in this mapping the expected output will be the distance values annotated as kilometres (km). For example:

```
<http://example.com/distance/1> <http://example.com/distance> "1927"^^<http://example.com/unit/km> .
<http://example.com/distance/3> <http://example.com/distance> "6285"^^<http://example.com/unit/km> .
<http://example.com/distance/2> <http://example.com/distance> "9"^^<http://example.com/unit/km> .
``` 
Currently, if I run such a mapping I got the following error: 

![image](https://user-images.githubusercontent.com/16767406/217593102-ea82f8d5-9cb4-489d-8a4f-518e45f1ce11.png)

#### Describe Alternatives you've Considered
Perhaps an alternative solution to this custom configuration could be to define another function that allows you to annotate any value to a custom data type. For example, in the case of the math_round function you could get the output integer value it generates and then customize that value using the additional function. Therefore we can use a nested configuration to first round the value and then customize that rounded value.

#### Additional Context
---

**Comment by arenas-guerrero-julian** [comment]
Hi @paoespinozarias ,

I made a change in 689a5bad1ce50bff5ee1f6557457249431dc0d7a. Please, could you try with the latest version from the repo?

**Comment by paoespinozarias** [comment]
Thanks @arenas-guerrero-julian !

It works perfectly :-)
