### ISSUE TITLE
BUG: fails when processing json files with other extensions 

### ISSUE THREAD

**Issue by cristianvasquez** [morph-kgc/morph-kgc#150]
Hi, thanks for this wonderful lib!
####  What Happens?

When one defines a Json source that does not have the 'json' extension, the mapping errors with: 

`UnboundLocalError: local variable 'data' referenced before assignment`

#### To Reproduce

A mapping for file.json 
```
    rml:logicalSource [
        rml:source "file.json";
        rml:referenceFormulation ql:JSONPath;
        rml:iterator "$.features[*].properties"
    ];
```
but named differently
```
    rml:logicalSource [
        rml:source "file.geojson";
        rml:referenceFormulation ql:JSONPath;
        rml:iterator "$.features[*].properties"
    ];
```

#### Environment (please complete the following information):
Ubuntu 22.04 LTS
 - Python version:  3.10
 - Morph-KGC version: v2.3.1

**Comment by arenas-guerrero-julian** [comment]
Thanks @cristianvasquez!

We could add `.geojson` as a valid json file extension, would that work?

**Comment by cristianvasquez** [comment]
For my specific case yes I think, but there will be other cases.

I imagined that the file type was derived from the reference formulation...

Other solution could be that the app errors telling the user 'unknown extension geojson'

**Comment by arenas-guerrero-julian** [comment]
morph-kgc uses the file extension to infer the type of reference formulation. Actually you can avoid using `rml:referenceFormulation` in your mapping:

```ttl
rml:logicalSource [
        rml:source "file.json";
        rml:iterator "$.features[*].properties"
    ];
```

I lean towards maintaining this behavior, but adding `.geojson` makes sense. I totally agree we should show some message instead of the current error, this is aligned with #63.

**Comment by cristianvasquez** [comment]
Sounds great! Thank you!

**Comment by arenas-guerrero-julian** [comment]
Now, when the file extension is not recognized, the reference formulation is used to detect the file type.
