### ISSUE TITLE
pip install morph-kgc[all] does not work

### ISSUE THREAD

**Issue by gkirtzou** [morph-kgc/morph-kgc#154]
#### Environment (please complete the following information):
 - OS: Ubuntu 20.04 LTS
 - Python version: 3.8.10

#### Morph-KGC Version
The latest available via pip install

#### Installation Method
Within a virtual enviroment tried to install morph-kgc via pip install. I have successfully install the morph-kgc, but since I wanted to use it with a relational db, I need to install the extra dependencies as it documented in the [documentation](https://morph-kgc.readthedocs.io/en/latest/documentation/#advanced-setup) . Unfortunately, this command
```pip install morph-kgc[mysql]```
does not to any available package, when I tried to remove the square brackets, 
```pip install morph-kgcmysql ```
I get the following error
```
^[[AERROR: Could not find a version that satisfies the requirement morph-kgcmysql (from versions: none)
ERROR: No matching distribution found for morph-kgcmysq
```
Which is the correct command to install the dependecies for MYSQL db? And which is the command to install the full package 
```pip install morph-kgc[all]```

**Comment by arenas-guerrero-julian** [comment]
Hi @gkirtzou ,

This is weird, I just tried `pip install morph-kgc[mysql]` and it is working for me. I am also on Ubuntu, maybe it is related be the python version.

Alternatively, if you want to use mysql you may use the basic morph-kgc installation:

```
pip install morph-kgc
```

And install separetely the drivers for mysql:

```
pip install pymysql
pip install cryptography
```

**Comment by arenas-guerrero-julian** [comment]
I am on `3.10.6`

**Comment by arenas-guerrero-julian** [comment]
I am closing this, but it can be potentially reopened if it occurs again
