### ISSUE TITLE
QST: Morph-KGC with logicalsource relational database working with R2RML mappings but not with RML

### ISSUE THREAD

**Issue by andreaalvarezp** [morph-kgc/morph-kgc#162]
Hello, I have a question about the differences between morph-kgc execution with R2RML and RML mappings. The same config file works with R2RML mappings but not wth RML mappings. The connection to the database is stablished, and the mappings are processed, but the number of triples generated is 0.

The R2RML mapping: 

```
rr:logicalTable [
    	rr:tableName "gene"
    ];
```

The RML mapping: 

```
rml:logicalSource [
    	rml:source "gene";
    	rml:referenceFormulation ql:SQL2008;
    ];
```

The config file includes 'main_dir', 'output_file', 'mappings' and 'db_url'.

How can I solve this?

**Comment by arenas-guerrero-julian** [comment]
Hi @andreaalvarezp ,

`rml:source` is for files (e.g. CSV files). For database tables RML uses `rr:tableName` (similar to R2RML). Your RML mapping should look as follows:

```ttl
rml:logicalSource [
    	rml:source "gene";
    	rml:referenceFormulation ql:SQL2008;
    ];
```
