### ISSUE TITLE
BUG: Morph does not generate triples with static subjects

### ISSUE THREAD

**Issue by dgarijo** [morph-kgc/morph-kgc#164]
####  What Happens?
Morph generates 0 triples, but it should generate at least one

#### To Reproduce
Use this rml mapping:
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ex: <http://example.com/ns#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix ecfo_instance: <https://w3id.org/ecfkg/i/mlco2/>.
@base <http://example.com/ns#>.

<#TransportMapping> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "./data/mlcalculator_impact_v2.csv" ;
    rml:referenceFormulation ql:CSV;
  ];

  rr:subjectMap [
    rr:constant
      "https://w3id.org/ecfkg/i/mlco2/MLCO2ImpactCalculator";
    rr:class ex:Stop
  ];

  rr:predicateObjectMap [
    rr:predicate rdfs:label;
    rr:objectMap [
      rr:constant ".dfgsdfg"
    ]
  ].
```
With this csv:
```
provider,providerName,offsetRatio,region,regionName,country_wikidata,country,state,city,impact_modified,impact,valid_from,valid_to,source_curated,source,PUE,PUE source,comment
gcp,Google Cloud Platform,100,asia-east1,,http://www.wikidata.org/entity/Q865,Taiwan,,Changhua County,0.557,557,2019-01-01T00:00:00,2019-12-31T23:59:59,www.electricitymap.org,"measured on  July 2, 2019 between 8 and 9 PM, EST on www.electricitymap.org",1.12,https://www.google.com/about/datacenters/efficiency/,Datacenter-specific
```
I just want to generate a triple unrelated to the contents of the file with the label. Morph recognizes the rules, but generates 0 triples:
```
INFO | 2023-05-04 18:35:32,475 | 2 mapping rules retrieved.
INFO | 2023-05-04 18:35:32,491 | Mapping partition with 2 groups generated.
INFO | 2023-05-04 18:35:32,491 | Maximum number of rules within mapping group: 1.
INFO | 2023-05-04 18:35:32,492 | Mappings processed in 0.269 seconds.
INFO | 2023-05-04 18:35:32,587 | Number of triples generated in total: 0.
INFO | 2023-05-04 18:35:32,588 | Materialization finished in 0.094 seconds.
```
As a result, I was expecting 1 triple to be created with the label for my constant subject. Now I have to create a separate file for those triples.

**Comment by dachafra** [comment]
@dgarijo small fix in the mapping. Following [R2RML spec](https://www.w3.org/TR/r2rml/#constant), the value of the subject if it is a constant must by an [IRI](http://www.w3.org/TR/2004/REC-rdf-concepts-20040210/#dfn-URI-reference), and there you are indicating that it's literal. I knew because the same issue happened in the [GTFS-Bench](https://github.com/oeg-upm/gtfs-bench/issues/142). So, the correct mapping then would be:
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ex: <http://example.com/ns#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix ecfo_instance: <https://w3id.org/ecfkg/i/mlco2/>.
@base <http://example.com/ns#>.

<#TransportMapping> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "./data/mlcalculator_impact_v2.csv" ;
    rml:referenceFormulation ql:CSV;
  ];

  rr:subjectMap [
    rr:constant
      <https://w3id.org/ecfkg/i/mlco2/MLCO2ImpactCalculator>;
    rr:class ex:Stop
  ];

  rr:predicateObjectMap [
    rr:predicate rdfs:label;
    rr:objectMap [
      rr:constant ".dfgsdfg"
    ]
  ].
```

In any case, with this mapping, the engine still fails, although if the objectMap is a reference instead of a constant it partially works (generates the triple from the objectMap but not the `rdf:type ex:Stop`)

**Comment by dgarijo** [comment]
Sorry, I regenerated the mapping manually. The original file is larger. Line 25 of https://github.com/TEC-Toolkit/cfkg/blob/main/BEIS-UK/mappings/rml/mlcalculator.rml_v2.ttl

**Comment by arenas-guerrero-julian** [comment]
This should be fixed in the next release.

As a more general RML question, I wonder whether `rml:logicalSource` should be optional, since it is not required in this case @dachafra @anaigmo.

**Comment by dgarijo** [comment]
good point

**Comment by anaigmo** [comment]
This issue is actually under discussion at [this issue](https://github.com/kg-construct/rml-core/issues/57). I'll bring it up as use case.

**Comment by KappaGi** [comment]
> This should be fixed in the next release.
> 
> As a more general RML question, I wonder whether `rml:logicalSource` should be optional, since it is not required in this case @dachafra @anaigmo.

It seems this is related to the constant value in the `rr:predicateObjectMap`. But there is also the following problem:

If I have a `rr:constant` uri value as subject in `rr:subjectMap` that has `rr:IRI` as `rr:termType` and assigned `rr:class`, morph does not generate the triplet <subject> <rdf:type> <class>

Will this fix also the previous case? Should I open another issue?

**Comment by KappaGi** [comment]
> This should be fixed in the next release.
> 
> As a more general RML question, I wonder whether `rml:logicalSource` should be optional, since it is not required in this case @dachafra @anaigmo.

Will this also solve the problem of not generating triplet `<https://w3id.org/ecfkg/i/mlco2/MLCO2ImpactCalculator> a ex:Stop`?
