### ISSUE TITLE
Error: Im trying to execute but gives error

### ISSUE THREAD

**Issue by titoarrabal** [morph-kgc/morph-kgc#168]
While i execute, it gaves me this error : 
C:\Users\Usuario\Desktop\TFG\Mapping\ComunidadMadrid\Meteorologicos>python3 -m morph_kgc config.ini
INFO | 2023-05-15 20:30:31,803 | 21 mapping rules retrieved.
INFO | 2023-05-15 20:30:31,881 | Mapping partition with 14 groups generated.
INFO | 2023-05-15 20:30:31,881 | Maximum number of rules within mapping group: 5.
INFO | 2023-05-15 20:30:31,881 | Mappings processed in 4.157 seconds.
multiprocessing.pool.RemoteTraceback:

UnboundLocalError: local variable 'data' referenced before assignment

**Comment by arenas-guerrero-julian** [comment]
Please, provide more details, such as the version of morph-kgc nd mappings.
