### ISSUE TITLE
Insight Trends Reloaded 

### ISSUE THREAD

**Issue by ollifdgmdg** [morph-kgc/morph-kgc#169]
First of all. What a great app. The thing is that I encounter an issue with Insight Trends relladed which is still there after the update to V1.3.8 When I go the configure app envirement wher I can find results of a trend I don't see any results when I use the 5 minutes time window. It is saying that there is only one number of used data points. This used to work. Also I'm not able to skip the zero data. 
![Screenshot_20230516_213144_Homey](https://github.com/morph-kgc/morph-kgc/assets/110771005/0cba8829-1a49-4b15-a018-8da997c6e143)

**Comment by arenas-guerrero-julian** [comment]
Hi @ollifdgmdg ,

How is this relate to Morph-KGC?

Julián

**Comment by ollifdgmdg** [comment]
Hello Julian. Sorry about this. I tried to go via Homey to a github link. That didn't work. So I tried another way. I don't see a way to reach you and I didn't like to mention anything about this at the comment at homey. Perhaps you can tell me to do it the right way. Hope also that you understand my issue with Insight trends reloaded. It used to work fine until I think a week ago. I'm now running on insight trends which is still working even after he quit updating it. Thanks for now. Really love this app. Can't do without. Regards Fred Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Julián Arenas Guerrero ***@***.***> Datum: 17-05-2023  09:26  (GMT+01:00) Aan: morph-kgc/morph-kgc ***@***.***> Cc: ollifdgmdg ***@***.***>, Mention ***@***.***> Onderwerp: Re: [morph-kgc/morph-kgc] Insight Trends Reloaded  (Issue #169) 
Hi @ollifdgmdg ,
How is this relate to Morph-KGC?
Julián
