### ISSUE TITLE
BUG: RML-star - multiple predicate-object-mappings not recognised in base of 2nd-level deeply nested triples

### ISSUE THREAD

**Issue by pawelostr** [morph-kgc/morph-kgc#174]
####  What Happens?
See https://github.com/morph-kgc/morph-kgc/issues/174#issuecomment-1600859952

~When attempting to generate any kind of 2nd level quote the engine fails (producing no double quoted triples most of the time, in some cases there will be one triple generated).~

#### To Reproduce
~Use the files in following Gist [mapping and data source](https://gist.github.com/pawelostr/f7ed8e7c413de9eb799878f9d615da70) - this is an example adopted from [RML-star spec](https://kg-construct.github.io/rml-star/spec/docs/#nested), where no 2nd level quoted triples are generated. 
Same problem happens with XML files and appropiate mappings.~

#### Environment (please complete the following information):
 - OS: macOS 13.4
 - Python version: 3.11
 - Morph-KGC version: 2.4.0 and 2.5.1

**Comment by arenas-guerrero-julian** [comment]
Hi @pawelostr ,

I just tried your example with Morph-KGC v 2.4.0 and with the latest version available in the repository and it is working correctly generating all the triples. I am on Ubuntu. CI test cases pass on python 3.11 and MacOS.

I wonder if it could be your MacOS version. Please try on another OS.

Julián

**Comment by pawelostr** [comment]
Hi Julián,

So I've tried the mappings on Windows 11 22H2 with Python 3.9.13 and in Google Colab, and unfortunatelly the result it still the same - no triples from `<#outerTriplesMap>` are generated.

Below is a script for Colab, in which exactly 0 triples are generated, as to exacerbate the problem I've switched `<#innerTriplesMap>` and `<#middleTriplesMap>` to `rml:NonAssertedTriplesMap`.

```
!pip install morph-kgc
!git clone https://gitlab.com/pawelostr/rdf-star-animals.git
!echo "[Something]" > /content/rdf-star-animals/config-temp.ini
!echo "mappings=animals.ttl" >> /content/rdf-star-animals/config-temp.ini
!cd /content/rdf-star-animals && python3 -m morph_kgc config-temp.ini
```

On a side note, I've tried almost every combination of NonAssertedTriplesMap, AssertedTriplesMap, TriplesMap, and all the combinations of prefixes from RML and R2RML to no avail.

**Comment by arenas-guerrero-julian** [comment]
Hi @pawelostr ,

I tried again and it is working.

Julián

**Comment by arenas-guerrero-julian** [comment]
Thanks for checking this @anaigmo

**Comment by pawelostr** [comment]
Hey @anaigmo @arenas-guerrero-julian, 

There was indeed an error in my original example, as I've mixed some old and new stuff, and yours works in both 2.5.1 and 2.6.0. 

For posteriority I'll leave a modified one that's fully on `rml` prefix `http://w3id.org/rml/`, that's cohesive with morph rml-star test cases as of 2.6.0.

[animals-full-rml.ttl.txt](https://github.com/morph-kgc/morph-kgc/files/11757272/animals-full-rml.ttl.txt)

**Comment by arenas-guerrero-julian** [comment]
This issue is related to #124

**Comment by pawelostr** [comment]
Unfortunately the original diagnosis (https://github.com/morph-kgc/morph-kgc/issues/174#issue-1750015430) was wrong,  and uploaded example mapping was not the representative of the issue at hand. 

> (producing no double quoted triples most of the time, in some cases there will be one triple generated)

only the second part is the problem, first it a problem of incorrect mappings that have been created during attemps at diagnosis of the bug.

#### What Happens? 

If a second level of deeply nestes quoted triples is attempted to be generated (`<< << < s p o > p1 o1 >> p2 o2 >>`) _and_ there's more than one `predicateObjectMap` (whether as a `predicateObjectMap` or as a class in `subjectMap`) in an `AssertedTriplesMap` or `NonAssertedTriplesMap`, only one triple is generated. 

#### To Reproduce

Run test/issues/issue_174 on a pre-pull request no [177](https://github.com/morph-kgc/morph-kgc/pull/177) (<=2.6.0) morph-kgc. 

#### Resolution 

pull request no [177](https://github.com/morph-kgc/morph-kgc/pull/177) fixes described problem and [178](https://github.com/morph-kgc/morph-kgc/pull/178) add additional tests
