### ISSUE TITLE
BUG: Issue #181 reported as closed but problem still persists

### ISSUE THREAD

**Issue by prashydee** [morph-kgc/morph-kgc#182]
####  What Happens?
The issue [#181](https://github.com/morph-kgc/morph-kgc/issues/181) is marked as closed/resolved but the problem still persists in my code. I've attached the data [test.csv](https://github.com/morph-kgc/morph-kgc/files/12012115/test.csv) .

#### To Reproduce
Using either of the the following mappings produces the same results, where strings are produced instead of IRI objects:

Output: 
~~~
@prefix ns1: <http://www.example.com/test/> .

ns1:Notification_A01 a ns1:Notification ;
    ns1:inferredCause "http://www.example.com/test/InferredCause_A01" .

ns1:Notification_A02 a ns1:Notification .

ns1:Notification_A03 a ns1:Notification ;
    ns1:inferredCause "http://www.example.com/test/InferredCause_A03" .

ns1:Notification_A04 a ns1:Notification ;
    ns1:inferredCause "http://www.example.com/test/InferredCause_A04" .

ns1:Notification_A05 a ns1:Notification .

ns1:Notification_A06 a ns1:Notification ;
    ns1:inferredCause "http://www.example.com/test/InferredCause_A06" .
~~~

Desired output:
~~~
@prefix ns1: <http://www.example.com/test/> .

ns1:Notification_A01 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A01 .

ns1:Notification_A02 a ns1:Notification .

ns1:Notification_A03 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A03 .

ns1:Notification_A04 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A04 .

ns1:Notification_A05 a ns1:Notification .

ns1:Notification_A06 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A06 .
~~~

This result is obtained when I apply the function to the objects, as shown below:
~~~
prefixes:
  xsd: "http://www.w3.org/2001/XMLSchema#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  ex: "http://www.example.com/test/"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

sources:
  test: [test.csv~csv]

mappings:
  notification:
    sources: test
    s: ex:Notification_$(Notification)
    po:
      - [rdf:type, ex:Notification]
      - p: ex:inferredCause
        o:
          - function: grel:controls_if
            parameters:
              - parameter: grel:bool_b
                value: "'$(CauseKey)' != 'None'"
              - parameter: grel:any_true
                value: ex:InferredCause_$(Notification)
            type: iri

~~~

The same result is produced when I map the subjects using the function, as shown below:

~~~
prefixes:
  xsd: "http://www.w3.org/2001/XMLSchema#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  ex: "http://www.example.com/test/"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

sources:
  test: [test.csv~csv]

mappings:
  notification:
    sources: test
    s: ex:Notification_$(Notification)
    po:
      - [rdf:type, ex:Notification]
      - p: ex:inferredCause
        o:
          - mappings: cause


  cause:
    sources: test
    s:
      - function: grel:controls_if
        parameters:
          - parameter: grel:bool_b
            value: "'$(CauseKey)' != 'None'"
          - parameter: grel:any_true
            value: ex:InferredCause_$(Notification)
        type: iri
    po:
      - [rdf:type, ex:Cause]
~~~

In the second case I would also expect to see that the 'causes' are of rdf:type ex:Cause which doesn't appear in the triples. 

For the sake of completion here is my python code for running the configuration:

~~~
import morph_kgc

CONFIG = """
    [DataSource1]
    mappings=test_mappings.yml
"""
graph = morph_kgc.materialize(CONFIG)
graph.serialize(destination="test_kg.ttl")
~~~

Please can you help? Thank you!

#### Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.10
 - Morph-KGC version: 2.6.2 (latest)
[test.csv](https://github.com/morph-kgc/morph-kgc/files/12012115/test.csv)

**Comment by prashydee** [comment]
CORRECTION:

My second set of mappings, in which the function is applied to the **subject**, actually works! It's just the application of the function to **objects** that gives me back strings, but that is still an issue. To be sure I even tried installing the latest commit of morph-kgc directly from the repository, but still got the same result.

At least for now, I can work by making sure that I use the function only on the subjects

**Comment by prashydee** [comment]
By the way, in this case I think I do actually need a function since I am not building the IRI from the same column as the one giving my boolean condition. In other words,  when the CauseKey is not empty I am building an IRI using the Notification column entry to give me my unique member of the class "ex:Cause". This is because the Notifcation column is unique while the CauseKey column is not unique.

**Comment by arenas-guerrero-julian** [comment]
> By the way, in this case I think I do actually need a function since I am not building the IRI from the same column as the one giving my boolean condition. In other words, when the CauseKey is not empty I am building an IRI using the Notification column entry to give me my unique member of the class "ex:Cause". This is because the Notifcation column is unique while the CauseKey column is not unique.

You are right.

@jatoledo could you please maybe test this on windows? Maybe the problem is the OS on my linux the desired output is generated.

**Comment by jatoledo** [comment]
Hi @arenas-guerrero-julian  and @prashydee.

I have tested with the first mapping and this is the output:

```
@prefix ns1: <http://www.example.com/test/> .

ns1:Notification_A01 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A01 .

ns1:Notification_A02 a ns1:Notification .

ns1:Notification_A03 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A03 .

ns1:Notification_A04 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A04 .

ns1:Notification_A05 a ns1:Notification .

ns1:Notification_A06 a ns1:Notification ;
    ns1:inferredCause ns1:InferredCause_A06 .

ns1:InferredCause_A01 a ns1:Cause .

ns1:InferredCause_A03 a ns1:Cause .

ns1:InferredCause_A04 a ns1:Cause .

ns1:InferredCause_A06 a ns1:Cause .

```

**Comment by prashydee** [comment]
Interesting. Then I don't really know why it is not working on my machine. I am going to let my colleaugues also try it out on their machines...

**Comment by prashydee** [comment]
Bingo! I tried first running `pip uninstall morph-kgc ` and then running `pip install git+https://github.com/morph-kgc/morph-kgc.git` to install the latest version of morph from the repository. Now both subjects and objects work with the functions. I guess it's necessary to first explicitly uninstall the existing version to replace it with the newest one.

**Comment by prashydee** [comment]
All good now!
