### ISSUE TITLE
QST: Dynamic formed IRI as subject

### ISSUE THREAD

**Issue by MaFi2000** [morph-kgc/morph-kgc#189]
####  What Happens?
I want to generate a uuid based IRI as subject and to add my predicateObjects to it.
Problem is that every triples has different subjects even if those are the same instances.

That is my output

`_:b4d4e7a0-5746-4be4-ba86-67b6b4c15a21 <http://www.example.co.uk/last_name> "Turcotte" .
_:7346acfd-908e-42f6-aa42-7b63605cfe80 <http://www.example.co.uk/last_name> "Parisian" .
_:32dadd9e-24a1-4a76-8213-8a180add4171 <http://www.example.co.uk/last_name> "Daugherty" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/rmsidentifier> "Edwin" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/rmsidentifier> "Kelley" .
_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/rmsidentifier> "Jewel" .`

That is the output I want to get/expect to get:
`_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/last_name> "Turcotte" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/last_name> "Parisian" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/last_name> "Daugherty" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/rmsidentifier> "Edwin" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/rmsidentifier> "Kelley" .
_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/rmsidentifier> "Jewel" .`

#### To Reproduce
`  
<#testuuid> 

    rml:logicalSource <#LogicalSource2> ;
    rr:subjectMap [
        fnml:execution <#GetUUID> ;
        rr:termType rr:BlankNode;
    ];
    rr:predicateObjectMap [
        rr:predicate ex:rmsidentifier;                     
        rr:objectMap [
            rml:reference "first_name"; 
        ];
    ];
    rr:predicateObjectMap [
        rr:predicate ex:last_name;                     
        rr:objectMap [
            rml:reference "last_name"; 
        ];
    ].
<#GetUUID>

    fnml:function <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#uuid> ; 
.

`

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04
 - Python version: 3.9.13
 - Morph KGC: 2.5.1

**Comment by arenas-guerrero-julian** [comment]
`uuid` is a non-deterministic function, so this is the expected behaviour.

What data source (e.g. relational database, CSV, JSON) are you working with?

**Comment by MaFi2000** [comment]
> `uuid` is a non-deterministic function, so this is the expected behaviour.
> 
> What data source (e.g. relational database, CSV, JSON) are you working with?

I am using Json and CSV. At the moment I am using a  workaround and transforming my sons and csv before starting the transformation, but I don't like this solution. Do you know how to dress this issue?

**Comment by arenas-guerrero-julian** [comment]
You can check #102 where this is being discussed.

For CSVs you can use [RML Views](https://oa.upm.es/73463/1/_2023___ESWC__RML_Tabular_Views.pdf) using the row number (`row_number()`), which is deterministic:

```ttl
<TriplesMap1>
 	rml:logicalSource [
                     rml:query """
                       SELECT COL1, row_number() over () AS ID
                       FROM 'path/to/my/file.csv'  """ ];
	rr:subjectMap [ rr:template "http://example.com/{ID}" ];
	rr:predicateObjectMap [
                       rr:predicate ex:col;
                       rr:objectMap [ rml:reference "COL1" ];
        ];
```

For JSON, if it not very complicated, you can do something similar, check [this blog post](https://duckdb.org/2023/03/03/json.html)

**Comment by arenas-guerrero-julian** [comment]
I close this issue, discussion can continue in #102
