### ISSUE TITLE
Support mappings for multi-valued cells

### ISSUE THREAD

**Issue by KappaGi** [morph-kgc/morph-kgc#190]
#### Is your Feature Request Related to a Problem?
Tabular data is often not limited to a single valuable pice of information per cell. We frequently found cases in which a single cell contains several values to be mapped. User defined functions in Morph are a very useful feature, but they can only "return" a single value each time it is called, meaning that subject/object maps based on the results of a function are limited to a single value returned. It would be nice if we could handle lists (arrays) as function's results whose values can be mapped individually.

#### Describe the Solution you'd Like
We could handle multi-valued cells making use of user defined functions that split the cell into several values, each of them acting as input for a mapping rule. The following illustrating example shows how this is handled by RML-Mapper ([link1](https://stackoverflow.com/questions/53715353/converting-a-csv-to-rdf-where-one-column-is-a-set-of-values), [link2](https://github.com/kg-construct/rml-questions/discussions/45#discussioncomment-6655385)):

Let's say we have an input CSV like:
```
col1,col2,col3
"A","B C D","John"
"M","X Y Z","Jack"
```
Which has several values in cells of column '"col2", so we want the transformation to generate the following RDF:
```
:A :aProperty "B", "C", "D".
:M :aProperty "X", "Y", "Z".
```
To do so, a user defined function is used to split values of "col2". Such function returns a list of elements, each of them able to be processed individually. The following RML mappings tackling such transformation are handled by RML-Mapper:
```
<#MyTriplesMap>
    a rr:TriplesMap;
    rml:logicalSource <#LogicalSource>;

    rr:subjectMap [
        rr:template "http://example.org/{col1}";
    ];

    rr:predicateObjectMap [
        rr:predicate ex:aProperty;
        rr:objectMap <#FunctionMap>;
    ];
.

<#FunctionMap>
    fnml:functionValue [
        rml:logicalSource <#LogicalSource>;
        rr:predicateObjectMap [
            rr:predicate fno:executes; 
            rr:objectMap [ 
                rr:constant grel:string_split 
            ];
        ];
        rr:predicateObjectMap [
            rr:predicate grel:valueParameter;
            rr:objectMap [ 
                rml:reference "col2" 
            ];
        ];
        rr:predicateObjectMap [
            rr:predicate grel:p_string_sep;
            rr:objectMap [ 
                rr:constant " ";
            ];
        ];
    ].
```
Considering that ```grel:string_split``` is a function that splits a string according to separator specified in parameter ```grel:p_string_sep```, the mappings will lead to the following triples being generated:
```
<http://example.org/A> <http://example.org/ns#aProperty> "B".
<http://example.org/A> <http://example.org/ns#aProperty> "C".
<http://example.org/A> <http://example.org/ns#aProperty> "D".
<http://example.org/M> <http://example.org/ns#aProperty> "X".
<http://example.org/M> <http://example.org/ns#aProperty> "Y".
<http://example.org/M> <http://example.org/ns#aProperty> "Z".
```

I am not aware about other possible solutions, just took this example as there is already a solution for this problem.

It would be nice to hear your thoughts on this. Thank you.
Un saludo.

**Comment by arenas-guerrero-julian** [comment]
We have a built-in function (`morph-kgc:string_split_explode`) for this. Take a look at [this test case](https://github.com/morph-kgc/morph-kgc/tree/main/test/rml-fnml/split_explode_null).

If you work this CSVs, you can also do this using [RML Tabular Views](https://oa.upm.es/73463/1/_2023___ESWC__RML_Tabular_Views.pdf), check an example in Section 5.2. You can also have a look at [this test case](https://github.com/morph-kgc/morph-kgc/tree/main/test/rmltv/RMLTVTC0026a), it is not exactly the same, but you can use *split* and *unnest*  functions in SQL to address your specific case.

**Comment by KappaGi** [comment]
Hello @arenas-guerrero-julian,

The built-in function used in the example test case solves the issue.

Thanks!
