### ISSUE TITLE
Out of memory parsing big file

### ISSUE THREAD

**Issue by ramcaat** [morph-kgc/morph-kgc#194]
####  What Happens?
When we parse a big file using morph .. it fails with Out of memory. I tried setting number of processors to 1 to minimize memory consumption but still it fails with the same OOM error similar to parallel processing 

File size - 6.5 GB
Number_of_processors=1
Memory taken during failure = 64.3GB

#### Environment (please complete the following information):
 - OS: rHEL 7.9
 - Python version: 3.8
 - Morph-KGC version: 2.6.2

**Comment by arenas-guerrero-julian** [comment]
Hi @ramcaat,

What is the file format (CSV, XML, ...)?

**Comment by ramcaat** [comment]
This is json. Also we downgraded to 2.1.1 and the same file goes through

**Comment by arenas-guerrero-julian** [comment]
Thanks, I will have a look

**Comment by arenas-guerrero-julian** [comment]
I will consider migrating to the jsonpath package https://github.com/night-crawler/jsonpath-rust-bindings (bindings recently created by @night-crawler)
