### ISSUE TITLE
Mandatory dependency sqlalchemy

### ISSUE THREAD

**Issue by idomingu** [morph-kgc/morph-kgc#221]
####  What Happens? 
After default installation of Morph-KGC, the "morph_kgc" library cannot be imported due to missing "sqlalchemy" dependency.

#### To Reproduce
```bash
pip install morph-kgc
```
Then execute:
```bash
>>> import morph_kgc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nacho/github/morph-kgc/src/morph_kgc/__init__.py", line 20, in <module>
    from .mapping.mapping_parser import retrieve_mappings
  File "/Users/nacho/github/morph-kgc/src/morph_kgc/mapping/mapping_parser.py", line 14, in <module>
    from ..data_source.relational_database import get_rdb_reference_datatype
  File "/Users/nacho/github/morph-kgc/src/morph_kgc/data_source/relational_database.py", line 12, in <module>
    from sqlalchemy import create_engine
ModuleNotFoundError: No module named 'sqlalchemy'
```

#### Environment (please complete the following information):
 - OS: MacOS 14.2.1
 - Python version: 3.11.5
 - Morph-KGC version: 2.6.4

**Comment by arenas-guerrero-julian** [comment]
Hi @idomingu,

I removed sqlalchemy as a dependency to make the library lighter. You can install it and the corresponding RDBMS drivers by:

```
pip install morph-kgc[postgresql]
```

For PostgreSQL, for other RDBMSs check the [documentation](https://morph-kgc.readthedocs.io/en/latest/documentation/#relational-databases_1).

**Comment by idomingu** [comment]
Hi @arenas-guerrero-julian, I believe this is a bug. My point is that the current code expects sqlalchemy to be installed, even if you don’t use the RDBMS drivers.

**Comment by arenas-guerrero-julian** [comment]
You are right @idomingu. I just fixed this, thanks for reporting the issue.
