### ISSUE TITLE
NULL value not ignored for Parquet file format

### ISSUE THREAD

**Issue by ramcaat** [morph-kgc/morph-kgc#227]
####  What Happens?
When we transform a file using RML which is in parquet format that has attribute value as NULL, morph kgc doesn't ignore and we get the triples generated as "None"

#### To Reproduce
1. Get a jSON with { value: null }
2. Convert to parquet
3. Transform with rml using standard mapping
4. The output value will be generated as {value : None}

#### Environment (please complete the following information):
 - OS: Windows, Linux
 - Python version: 3.9
 - Morph-KGC version:2.6.2

**Comment by arenas-guerrero-julian** [comment]
Can you provide an example of your data? I think that is not a Null value, but a string which looks like encoding a null value.

You can use the `na_values` in the configuration file to specify which strings you want to be interpreted as null.

**Comment by ramcaat** [comment]
I used na_values to ignore None which comes from parquet. The null is ignored in 2.1.1 but not in higher versions.  Example of data is given below

`{
"resourceID": "arn::ec2::Instance,
"resourceName" : "ec2"
"moduleName" : null,
"moduleID" : null
}
`
This transforms into moduleName: None and moduleID : None.

**Comment by arenas-guerrero-julian** [comment]
Is this entire JSON a value in a Parquet column?

Maybe you can try to use **moduleID : None** in the `na_values` parameter.

**Comment by ramcaat** [comment]
OK I will use na-values but was wondering why it worked in 2.1.1 so thought it will be a bug.
