### ISSUE TITLE
Output to Kafka topic doesn't seem to work

### ISSUE THREAD

**Issue by david-martinez-garcia** [morph-kgc/morph-kgc#228]
Hello,

I have a small testbed where I use Morph-KGC to generate RDF triples from a JSON file.

Until now, I have been writing the resulting knowledge graph to a text file without issues. Now, I want to output the same RDF triples to a Kafka topic. I have changed my ```config.ini``` file accordingly, but it doesn't seem to work. I can see from the execution logs that the materialization completes, but when I try to consume messages from the Kafka topic, it is empty. I include the content of my ```config.ini``` file:

```
[DEFAULT]

[CONFIGURATION]
output_kafka_server: kafka:9092
output_kafka_topic: knowledge-graphs
mapping_partitioning: no

[LDAPDataSource]
mappings: /files/input/mappings.yaml
```

Do you have any idea about what might be wrong? I am using the latest version of Morph installed via PIP, and this problem appears no matter how I define my testbed: in Docker Compose or by using local binaries and services.

Thanks in advance.

Kind regards.

**Comment by arenas-guerrero-julian** [comment]
@LuciaCabanillasRodriguez any idea what can it be?

**Comment by LuciaCabanillasRodriguez** [comment]
Have you tried removing the "/" before "files" in the path of your mapping file in the config.ini file? Sometimes, relative paths can cause issues on certain systems. Additionally, ensure that the Kafka server address is pointing correctly and that Morph-KGC is successfully connected to Kafka. You can verify this by checking the Morph-KGC logs to see if there are any successful connection messages or Kafka-related errors.

The expected log messages should resemble something like this:

```
INFO | 2024-04-02 15:37:21,812 | <BrokerConnection node_id=1001 host=ip:9092 <connecting> [IPv4 ('ip', 9092)]>: Connection complete.
INFO | 2024-04-02 15:37:21,812 | <BrokerConnection node_id=bootstrap-0 host=ip:9092 <connected> [IPv4 ('ip', 9092)]>: Closing connection.
```

Additionally, if you could provide more details on how you are consuming messages from Kafka, it would be helpful for further troubleshooting. Understanding your Kafka consumer setup could provide insights into any potential issues on the consumer side.

I hope these additional steps help you resolve the problem! If you need further assistance, feel free to ask.

**Comment by LuciaCabanillasRodriguez** [comment]
@david-martinez-garcia Thanks for sharing your experience! It's not uncommon for optional dependencies to be missed during installation, and kafka-python is indeed one of those optional dependencies for Morph. Glad to hear you were able to resolve the issue . If you encounter any further issues or have any questions, feel free to ask!
