### ISSUE TITLE
Use of YARRRML with a Pandas dataframe as source

### ISSUE THREAD

**Issue by IshanDindorkar** [morph-kgc/morph-kgc#247]
Hello,

We have a requirement where the data has to be loaded using a Pandas data frame. Here is the pipeline we are trying to build:
Data source (Impala) -> SQL Query -> Python Dataframe -> mappings in YARRRML (currently only in RML) -> RDF
We are following these URLs to get an idea of working with data frames using morph-kgc:
https://github.com/morph-kgc/morph-kgc/blob/main/examples/dataframe/kg_generation.py
https://github.com/morph-kgc/morph-kgc/blob/main/examples/dataframe/mapping.rml.ttl

The usage of YARRRML format is advised strongly for the mapping configuration and we also liked it while working on the topic of loading data from Oracle database. Currently the example is using RML format. In that case, can we use YARRRML to map a Dataframe?

Please share your thoughts.

Thank you.

Sincerely,
Ishan Dindorkar

**Comment by arenas-guerrero-julian** [comment]
Hi @IshanDindorkar,

It is not possible to work right now with a Pandas Dataframe and YARRRML.

However, for your pipeline with Impala I think it is much better solution to implement an Impala connector in Morph-KGC. That way you could use YARRRML with SQL queries and you woud significantly simplify your pipeline.

**Comment by igrangel** [comment]
@arenas-guerrero-julian thanks for your quick answer. Your completely right, that would improve our pipeline. I assume that implementing that in Impala will take quite a while right?

**Comment by arenas-guerrero-julian** [comment]
I have to check but I think it would not take a lot. I can maybe take a look in the next weeks.

**Comment by igrangel** [comment]
@arenas-guerrero-julian thanks a lot for your support.

**Comment by arenas-guerrero-julian** [comment]
I have created an specific issue for Impala #251
