### ISSUE TITLE
XSD mapping -- UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by dhouib** [morph-kgc/morph-kgc#252]
Hello, 
I need to map an XSD file to RDF. I'm not sure if Morph-KGC can parse an XSD file because I get results when using an XML file, but when I switch to an XSD file, I encounter the error: Error in materializing RDF: local variable 'data' referenced before assignment. Can you confirm if Morph-KGC supports XSD mapping?
 morph_kgc Version: 2.7.0.
Thanks

**Comment by arenas-guerrero-julian** [comment]
Hi @dhouib,

I am unfamiliar with XSD. Is an XSD file a valid XML file?

**Comment by dhouib** [comment]
Yes, an XSD (XML Schema Definition) file is indeed a valid XML file.

XSD files are used to define the structure, constraints, and data types of XML documents. They follow the XML syntax and are written in XML markup language themselves. XSD files are commonly used to validate the structure and content of XML documents.

**Comment by arenas-guerrero-julian** [comment]
In that case, please, try changing the extension of the file to `.xml` (in the case that other is being used).

**Comment by arenas-guerrero-julian** [comment]
Hi @dhouib ,

This the solution work? Can this be closed?
