### ISSUE TITLE
Carga incompleta de los datos al poblar el Grafo de conocimiento usando: un mapping .yarrrml y un csv

### ISSUE THREAD

**Issue by deliamoreno2295** [morph-kgc/morph-kgc#257]
Buen día,

a través de la herramienta Mapheator genero un archivo de mapping YARRRML para posteriormente poblar el KG usando MORPH KGC y cargar el archivo ttl en GraphDB para finalmente ejecutar consultas SPARQL. Recientemente decidí realizar una con una validación de la cantidad de datos para las diferentes clases de la ontología comenzando con FUSION GENE realizando los siguientes pasos:
1. Realizando un conteo de los valores en el csv, de los distintos elementos de la columna: 'gene_fusion' que resulta en un valor de: 4267.
2. Finalmente en GraphDB ejecuto la siguientes consulta SPARQL:
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX bao: <http://www.bioassayontology.org/bao#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mesh: <http://phenomebrowser.net/ontologies/mesh/mesh.owl#>

SELECT (COUNT(DISTINCT ?gf_name) AS ?uniqueGFNames)
WHERE {
  ?gda sio:SIO_000628 ?gene, ?disease;
       dcterms:identifier ?gda_id.
  ?gene a ncit:C16612;
        dcterms:identifier ?geneID;
        rdfs:label ?gene_name.
  ?disease rdf:type ncit:C7057;
           dcterms:identifier ?disease_id;
           rdfs:label ?disease_name;
           bao:BAO_0090007 ?IRIorg.
  ?IRIorg rdf:type ncit:C14250;
          dcterms:identifier ?orgnism_id;
          rdfs:label ?organism_name.
  ?biomarker rdfs:subClassOf ?gda.
  ?gdalt rdfs:subClassOf ?biomarker.
  ?gdalt sio:SIO_000008 ?chr, ?gf.
  ?chr rdf:type sio:SIO_001348;
       dcterms:identifier ?chr_id;
       rdfs:label ?chr_name.
  ?gf rdf:type sio:SIO_001349;
      dcterms:identifier ?gf_id;
      rdfs:label ?gf_name.
} me resultan solo 1854 registros
Adjunto los archivos utilizados.
[KG.zip](https://github.com/user-attachments/files/15545517/KG.zip)

**Comment by arenas-guerrero-julian** [comment]
Hola @deliamoreno2295 ,

No veo nada raro. Creo que el problema es validar el output con una SPARQL query. En la query que adjuntas hay joins que puede que se estén eliminando resultados y por eso obtienes menos valores. Puedes probar con:

```
SELECT DISTINCT ?gf_name
WHERE {
  ?gf rdf:type sio:SIO_001349;
  rdfs:label ?gf_name.
}
```

En general, intenta depurar reglas de maneras más acotada para ver qué falla. Comprueba qué valores de gene_fusion no están en el resultado de la consulta, probablemente los joins están haciendo que se eliminen.

**Comment by deliamoreno2295** [comment]
Muchas gracias @arenas-guerrero-julian, revisare lo que me comentas.
