### ISSUE TITLE
Referencing objects from two mappings files with different logical sources

### ISSUE THREAD

**Issue by maqboolkhan** [morph-kgc/morph-kgc#270]
I have two mappings files

locations_mapping.ttl
```
....
....

<LocationMapping_JSON> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "venue.json" ;
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.b[*]" ;
  ];

....
....

```

venue_mapping.ttl
```
....
....

<VenueMapping_JSON> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "venue.json" ;
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.b[*]" ;
  ];

rr:predicateObjectMap [
    rr:predicate ex:latlong;
    rr:objectMap [
      rr:parentTriplesMap <LocationMapping_JSON>
    ]
  ];
....
....

```

INI
```
[DataSource1]
mappings: venue_mapping.ttl locations_mapping.ttl
```

Notice both mapping files are reading same json file and venue_mapping.ttl has reference to `LocationMapping_JSON`. This scenario works fine.

But if these two mapping files read data from different sources I am getting `Index out of range` error! **(This the main problem)**

So I thought do another experiment.
I removed reference to `<LocationMapping_JSON>` from `venue.json` and kept different json sources in both mapping file and it works!

This made everything more weird. At this point, I dont know if it has something do with RML specs or it is Morph-kgc bug or something?

Much thanks
Great work already :)

**Comment by arenas-guerrero-julian** [comment]
You are missing the join condition in the referencing object map (ROM). If the triples maps involved in a ROM have the same source the join condition may not be needed. However, if the sources are different the join is required.

**Comment by arenas-guerrero-julian** [comment]
You can take a look to the R2RML spec https://www.w3.org/TR/r2rml/#foreign-key. For JSON you can take a look to this example https://github.com/morph-kgc/morph-kgc/tree/main/test/rml-core/json/RMLTC0009a .

**Comment by maqboolkhan** [comment]
Thank you so much 👍  and it solved my problem
