### ISSUE TITLE
XML: If a certain section of data is missing in file then code fails

### ISSUE THREAD

**Issue by manikyab** [morph-kgc/morph-kgc#274]
####  What Happens?
If in XML file a attribute or a property is missing then the code fails (As thse fields can be optional in the given data).
Multi Level iterator are not able to find the data even if it exist in sample file

#### To Reproduce
Steps to reproduce the behavior. If possible include sample data, mappings and configuration used.
Sample Error received
![image](https://github.com/user-attachments/assets/3678289e-c719-4500-b438-26cc753c48c5)

The mapping and file I can share over mail.

#### Environment (please complete the following information):
 - OS: Mac:Sonoma 14.5
 - Python version: 3.10.x
 - Morph-KGC version: 2.8.0

**Comment by arenas-guerrero-julian** [comment]
Hi @manikyab ,

Could you provide example mappings and data to reproduce the issue?

**Comment by arenas-guerrero-julian** [comment]
Hi @manikyab:

Please, send me by email the mappings and data to reproduce the issue.

**Comment by manikyab** [comment]
Hi @arenas-guerrero-julian 
I have shared it over mail
Please  check your mail

Regards
Manikya

**Comment by arenas-guerrero-julian** [comment]
Hi @manikyab ,

I took a look at the mappings and data. Unfortunately, they are too large to identify where the problem comes from. I created a simpler example to check whether the issue you refer to actually occurs:

XML file:

```xml
<?xml version="1.0"?>

<countries>
  <country>
    <CountryCode>1</CountryCode>
    <Name>Bolivia, Plurinational State of</Name>
    <ISO3166>BO</ISO3166>
  </country>
  <country>
    <CountryCode>2</CountryCode>
    <Name>Ireland</Name>
    <ISO3166>IE</ISO3166>
  </country>
  <country>
    <CountryCode>3</CountryCode>
    <Name>Saint Martin (French part)</Name>
  </country>
</countries>
```

Mapping:

```ttl
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://w3id.org/rml/> .
@prefix activity: <http://example.com/activity/> .
@base <http://example.com/base/> .

<TriplesMap1>
  a rml:TriplesMap;

  rml:logicalSource [
    rml:source "country_info.xml";
    rml:referenceFormulation rml:XPath;
    rml:iterator "/countries/country"
  ];

  rml:subjectMap [ rml:template "http://example.com/{CountryCode}/{Name}" ];

  rml:predicateObjectMap [
    rml:predicate ex:code ;
    rml:objectMap [ rml:reference "ISO3166"; rml:termType rml:Literal]
  ] .
```

Output:

```ttl
<http://example.com/2/Ireland> <http://example.com/code> "IE" .
<http://example.com/1/Bolivia%2C%20Plurinational%20State%20of> <http://example.com/code> "BO" .
```

There is some missing data for the reference `ISO3166`, but the expected output is obtained without error.
