### ISSUE TITLE
QST: Unable to run the example

### ISSUE THREAD

**Issue by bnsapkota** [morph-kgc/morph-kgc#77]
I tried to run the example but I am unable to run following rules. It produces nothing.

map:om_013 a rr:ObjectMap;
    rml:reference "country.*.label";
    rr:termType rr:Literal.
map:om_014 a rr:ObjectMap;
    rml:reference "instance.*.license";

**Comment by ArenasGuerreroJulian** [comment]
Hi @bnsapkota ,

Please, provide your full mapping, you are missing the logicalSource, subject and predicate map. If possible, please provide also a sample of the data source.

**Comment by bnsapkota** [comment]
mapping file:
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix map: <http://mapping.example.com/>.

map:language_000 rml:reference "language.code".

map:map_Paper_000 rml:logicalSource map:source_000;
    a rr:TriplesMap;
    rdfs:label "Paper";
    rr:subjectMap map:s_001;
    rr:predicateObjectMap map:pom_005, map:pom_009, map:pom_013, map:pom_014.

map:om_005 a rr:ObjectMap;
    rr:constant "https://w3id.org/okn/os/o/Paper";
    rr:termType rr:IRI.

map:om_009 a rr:ObjectMap;
    rml:reference "language.label";
    rr:termType rr:Literal.

map:om_013 a rr:ObjectMap;
    rml:reference "country.*.label";
    rr:termType rr:Literal.
map:om_014 a rr:ObjectMap;
    rml:reference "instance.*.license";
    rr:termType rr:Literal.

map:pm_000 a rr:PredicateMap;
    rr:constant rdf:type.
map:pm_001 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/fullname>.
map:pm_002 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/name>.
map:pm_003 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/surname>.
map:pm_004 a rr:PredicateMap;
    rr:template "https://w3id.org/okn/os/o/{pid.id.scheme}ID".
map:pm_005 a rr:PredicateMap;
    rr:constant rdf:type.
map:pm_006 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/title>.
map:pm_007 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/subtitle>.
map:pm_008 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/description>.
map:pm_009 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/language>.
map:pm_010 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/format>.
map:pm_011 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/publicationDate>.
map:pm_012 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/type>.
map:pm_013 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/country>.
map:pm_014 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/license>.
map:pm_015 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/publisher>.
map:pm_016 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/source>.
map:pm_017 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/has_id>.
map:pm_018 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/has_id>.
map:pm_019 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/has_id>.
map:pm_020 a rr:PredicateMap;
    rr:constant rdf:type.
map:pm_021 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/source>.
map:pm_022 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/identifier>.
map:pm_023 a rr:PredicateMap;
    rr:constant rdf:type.
map:pm_024 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/source>.
map:pm_025 a rr:PredicateMap;
    rr:constant <https://w3id.org/okn/os/o/identifier>.

map:pom_005 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_005;
    rr:objectMap map:om_005.
map:pom_009 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_009;
    rr:objectMap map:om_009.
map:pom_013 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_013;
    rr:objectMap map:om_013.
map:pom_014 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_014;
    rr:objectMap map:om_014.

map:rules_000 a <http://rdfs.org/ns/void#Dataset>;
    <http://rdfs.org/ns/void#exampleResource> map:map_Paper_000.
map:s_000 a rr:SubjectMap;
    rr:template "https://w3id.org/okn/os/i/author/{fullname}".
map:s_001 a rr:SubjectMap;
    rr:template "https://w3id.org/okn/os/i/paper/{id}".
map:s_002 a rr:SubjectMap;
    rr:template "https://w3id.org/okn/os/i/idType/{id}".
map:s_003 a rr:SubjectMap;
    rr:template "https://w3id.org/okn/os/i/idType/{value}".
map:source_000 a rml:LogicalSource;
    rdfs:label "main-source";
    rml:source "data/health/clean/json/aggregated/data.json";
    rml:iterator "$.*";
    rml:referenceFormulation ql:JSONPath.

sample data:
[{
    "author": [
        {
            "fullname": "Ana Iglesias-Molina",
            "rank": 1
        },
        {
            "fullname": "David Chaves-Fraga",
            "rank": 2
        },
        {
            "fullname": "Oscar Corcho",
            "rank": 3
        },
        {
            "fullname": "Julián Arenas-Guerrero",
            "pid": {
                "id": {
                    "scheme": "orcid",
                    "value": "0000-0002-3029-6469"
                },
                "provenance": {
                    "provenance": "Harvested",
                    "trust": "0.91"
                }
            },
            "rank": 4
        }
    ],
    "bestaccessright": {
        "code": "abcdef",
        "label": "RESTRICTED",
        "scheme": "http://example.com/hahdawlrh"
    },
    "contributor": [],
    "country": [
        {
            "code": "ES",
            "label": "Spain",
            "provenance": {
                "provenance": "123456789",
                "trust": "0.85"
            }
        }
    ],
    "coverage": [],
    "dateofcollection": "2021-01-01",
    "description": [
        "RDF-star was recently proposed as a convenient representation to annotate statements in RDF with metadata by introducing the so-called RDF-star triples, bridging the gap between RDF and property graphs. However, even though there are many solutions to generate RDF graphs, there is no systematic approach so far to generate RDF-star graphs from heterogeneous data sources. In this paper, we propose RML-star, an extension of the RML mapping language to generate RDF-star. We introduce the extension of the RML ontology and the associated specification with representative examples."
    ],
    "format": [
        "application/pdf","a"
    ],
    "id": "2836412",
    "instance": [
        {
            "accessright": {
                "code": "r28934hdha",
                "label": "RESTRICTED",
                "scheme": "UNKNOWN"
            },
            "publicationdate": "2021-07-01",
            "refereed": "UNKNOWN",
            "type": "Article",
            "url": [
                "http://example.com/wqheu2byrfd"
            ]
        },
        {
            "refereed": "UNKNOWN",
            "type": "UNKNOWN",
            "url": [
                "http://example.com/w3895ryhlalf"
            ]
        },
        {
            "publicationdate": "2021-10-21",
            "refereed": "UNKNOWN",
            "type": "Other literature type",
            "url": [
                "http://example.com/hahdawlrhf3wuoybtr98als"
            ]
        }
    ],
    "language": {
        "code": "eng",
        "label": "English"
    },
    "lastupdatetimestamp": 1618221358260,
    "maintitle": "A High-Level Ontology Network for ICT Infrastructures",
    "originalId": [
        "oa219846fsdkfuw3h8r2432",
        "081297465",
        "218424100125",
        "892114652"
    ],
    "pid": [
        {
            "scheme": "doi",
            "value": "fsdfhnksjer939123474"
        },
        {
            "scheme": "handle",
            "value": "824hdddhqon3y84vbya"
        },
        {
            "scheme": "pmid",
            "value": "892daskjdw111"
        }
    ],
    "publicationdate": "2021-1-21",
    "publisher": "American Chemical Society",
    "type": "publication"
}]

**Comment by ArenasGuerreroJulian** [comment]
With morph-kgc v2.2.0 I am getting the following output:

```
<https://w3id.org/okn/os/i/author/Oscar%20Corcho> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/Author>.
<https://w3id.org/okn/os/i/author/Ana%20Iglesias-Molina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/Author>.
<https://w3id.org/okn/os/i/author/David%20Chaves-Fraga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/Author>.
<https://w3id.org/okn/os/i/author/Juli%C3%A1n%20Arenas-Guerrero> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/Author>.
<https://w3id.org/okn/os/i/paper/2836412> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/Paper>.
<https://w3id.org/okn/os/i/idType/824hdddhqon3y84vbya> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/idType>.
<https://w3id.org/okn/os/i/idType/892daskjdw111> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/idType>.
<https://w3id.org/okn/os/i/idType/fsdfhnksjer939123474> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/okn/os/o/idType>.
<https://w3id.org/okn/os/i/idType/824hdddhqon3y84vbya> <https://w3id.org/okn/os/o/identifier> "824hdddhqon3y84vbya".
<https://w3id.org/okn/os/i/idType/824hdddhqon3y84vbya> <https://w3id.org/okn/os/o/source> "handle".
<https://w3id.org/okn/os/i/idType/fsdfhnksjer939123474> <https://w3id.org/okn/os/o/identifier> "fsdfhnksjer939123474".
<https://w3id.org/okn/os/i/idType/fsdfhnksjer939123474> <https://w3id.org/okn/os/o/source> "doi".
<https://w3id.org/okn/os/i/idType/892daskjdw111> <https://w3id.org/okn/os/o/source> "pmid".
<https://w3id.org/okn/os/i/idType/892daskjdw111> <https://w3id.org/okn/os/o/identifier> "892daskjdw111".
<https://w3id.org/okn/os/i/author/Juli%C3%A1n%20Arenas-Guerrero> <https://w3id.org/okn/os/o/fullname> "Julián Arenas-Guerrero".
<https://w3id.org/okn/os/i/author/Oscar%20Corcho> <https://w3id.org/okn/os/o/fullname> "Oscar Corcho".
<https://w3id.org/okn/os/i/author/Juli%C3%A1n%20Arenas-Guerrero> <https://w3id.org/okn/os/o/orcidID> "0000-0002-3029-6469".
<https://w3id.org/okn/os/i/author/David%20Chaves-Fraga> <https://w3id.org/okn/os/o/fullname> "David Chaves-Fraga".
<https://w3id.org/okn/os/i/author/Ana%20Iglesias-Molina> <https://w3id.org/okn/os/o/fullname> "Ana Iglesias-Molina".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/description> "RDF-star was recently proposed as a convenient representation to annotate statements in RDF with metadata by introducing the so-called RDF-star triples, bridging the gap between RDF and property graphs. However, even though there are many solutions to generate RDF graphs, there is no systematic approach so far to generate RDF-star graphs from heterogeneous data sources. In this paper, we propose RML-star, an extension of the RML mapping language to generate RDF-star. We introduce the extension of the RML ontology and the associated specification with representative examples.".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/type> "publication".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/publisher> "American Chemical Society".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/format> "a".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/format> "application/pdf".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/publicationDate> "2021-1-21".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/title> "A High-Level Ontology Network for ICT Infrastructures".
<https://w3id.org/okn/os/i/paper/2836412> <https://w3id.org/okn/os/o/language> "English".

```

**Comment by bnsapkota** [comment]
@ArenasGuerreroJulian, thanks for the explanation. I was only interested to check whether` instance.*.license` works. Therefore, I removed everything from the original mapping except the rules what handles `country.*.lable` and instance.*.license`. But it produces nothing, I am not sure what went wrong.
